version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=${NODE_ENV}

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_URL=http://localhost:8080
